name: Lint

on:
    push:
        branches: main
    pull_request:
        branches: "*"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: Install dependencies
              run: yarn
            - name: Lint Solidity
              run: yarn lint
